### ISSUE TITLE
Error when updating the active learner

### ISSUE THREAD

**Issue by Jotanator** [jacobmarks/active-learning-plugin#4]
Hello, 

I followed the steps in the github where I have a voxel51 dataset and no labels. I didn't use the zero-shot annotation because the images I have it won't perform well so I manually annotated around 2K images and my hope was to use this to speed up the annotation process using active learning. I revised the predictions that the active learner made and corrected many that where wrong. But when trying to update the learner it gave me the following error:

```
Error occurred during operator execution
Traceback (most recent call last):
  File "/opt/miniconda3/envs/dermPipe/lib/python3.9/site-packages/fiftyone/operators/executor.py", line 277, in execute_or_delegate_operator
    result = await do_execute_operator(operator, ctx, exhaust=exhaust)
  File "/opt/miniconda3/envs/dermPipe/lib/python3.9/site-packages/fiftyone/operators/executor.py", line 319, in do_execute_operator
    result = await (
  File "/opt/miniconda3/envs/dermPipe/lib/python3.9/site-packages/fiftyone/core/utils.py", line 2317, in run_sync_task
    return await loop.run_in_executor(_get_sync_task_executor(), func, *args)
  File "/opt/miniconda3/envs/dermPipe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tapiasj/fiftyone/__plugins__/@jacobmarks/active_learning/__init__.py", line 481, in execute
    teach_learner(ctx.dataset)
  File "/home/tapiasj/fiftyone/__plugins__/@jacobmarks/active_learning/active_learning.py", line 237, in teach_learner
    learner = cache["learner"]
KeyError: 'learner'
```

Not entirely sure how to deal with this error and didn't see it in any of the issues in the github. Any help would be appreciated.

**Comment by jacobmarks** [comment]
Hi @Jotanator , thanks for logging this, and awesome to hear that you've annotated all of those samples! The current implementation of the plugin uses caching to store details about the active learning object. This means that if you leave your python session, relaunch, and try to run the teaching operator, you will get the error you identified. To resolve this, just recreate the active learner, but instead of using the original annotations, use the outputs from the most recent round of predicted labels from the active learning before you closed your session.

I'm currently bandwidth limited, but if/when I or someone else has time, a solution to this would be to swap out the caching mechanism for FiftyOne's [Custom Runs](https://docs.voxel51.com/plugins/developing_plugins.html#storing-custom-runs), which persist info like this beyond the given session. This is already being used in other plugins, like the [Albumentations plugin](https://github.com/jacobmarks/fiftyone-albumentations-plugin), and the [Clustering plugin](https://github.com/jacobmarks/clustering-plugin). 

Closing this for now, but feel free to reopen the issue if the fix above doesn't resolve it for you :)
